Added error messages and better error handling to build_gpgme. Fixed some path issues when building it outside the MacGPGME project.

diff --git a/Utilities/build_gpgme b/Utilities/build_gpgme
--- a/Utilities/build_gpgme
+++ b/Utilities/build_gpgme
@@ -1,14 +1,18 @@
 #!/bin/bash
 
-PREFIX="${TARGET_BUILD_DIR}/../dist"
-SOURCES="${TARGET_BUILD_DIR}/../sources"
+if [ "${TARGET_BUILD_DIR}" == "" ]; then
+    BASE=`pwd`
+else
+    BASE="${TARGET_BUILD_DIR}/.."
+fi
+
+PREFIX="${BASE}/dist"
+SOURCES="${BASE}/sources"
 
 GETTEXT_VERSION="0.18.1.1"
 LIBGPG_ERROR_VERSION="1.8"
 LIBASSUAN_VERSION="2.0.0"
 GPGME_VERSION="1.3.0"
-
-
 
 # Download the source code and unpack it.
 function fetch {
@@ -16,106 +20,214 @@ function fetch {
 	file=$(basename $url)
 	dir=$2
 	
-	if [ ! -f "$file" ]; then
-	
-	    curl -O $url
-	    
+	if [ -f "$file" ]; then
+	    return;
 	fi
+	
+	curl -O $url
+	
+	if [ $? -ne 0 ]; then
+	    bailout "Failed to download source at $url";
+	fi
+	
+	extract "$file" "$2"
+}
 
-    if [ ! -d "$dir" ]; then
-        
-        if [ "$(echo $file | awk -F . '{print $NF}')" == "gz" ]; then
-    	    tar xzf $file
-        else
-    	    tar xjf $file
-        fi
+# Extract the source code.
+function extract {
+    file=$1
+    dir=$2
+    
+    if [ -d "$dir" ]; then
+        return;
     fi
+    
+    ext=$(echo $file | awk -F . '{print $NF}')
+    
+    if [ "$ext" == "gz" ]; then
+        tar xzf $file
+        ret=$?
+    else
+        tar xjf $file
+        ret=$?
+    fi
+    
+    if [ $ret -ne 0 ]; then
+        bailout "Failed to extract: $file"
+    fi
+}
+
+function bailout {
+    msg=$1
+    
+    echo "build_gpgme error: $msg"
+    exit 1;
 }
 
 # Build the library.
 function build_gettext {
     # Only build if the binary doesn't exist already.
-    if [ ! -f "$PREFIX/bin/gettext" ]; then
-        version=$1-$2
-    	fetch "http://ftp.gnu.org/gnu/gettext/${version}.tar.gz" $1
-	
-    	pushd "$version" 1> /dev/null
-	
-    	CFLAGS="-isysroot /Developer/SDKs/MacOSX10.6.sdk -arch x86_64 -arch i386" \
-            ./configure --prefix="$PREFIX" --disable-shared --disable-dependency-tracking \
-            --disable-java --disable-native-java --disable-csharp \
-            --with-included-gettext --with-included-glib \
-            --with-included-libcroco --with-included-libxml --disable-libasprintf \
-            1> /dev/null
-    
-        make install 1> /dev/null
-    
-        popd 1> /dev/null
+    if [ -f "$PREFIX/bin/gettext" ]; then
+        return;
     fi
+    
+    version=$1-$2
+    fetch "http://ftp.gnu.org/gnu/gettext/${version}.tar.gz" $1
+	
+	# Check if the package was successfully extracted
+	if [ ! -d "$version" ]; then
+	    bailout "$version directory doesn't exist."
+	fi
+	
+	pushd "$version" 1> /dev/null
+	
+	CFLAGS="-isysroot /Developer/SDKs/MacOSX10.6.sdk -arch x86_64 -arch i386" \
+        ./configure --prefix="$PREFIX" --disable-shared --disable-dependency-tracking \
+        --disable-java --disable-native-java --disable-csharp \
+        --with-included-gettext --with-included-glib \
+        --with-included-libcroco --with-included-libxml --disable-libasprintf \
+        1> /dev/null
+    
+    ret=$?
+    
+    if [ $ret -ne 0 ]; then
+        bailout "$version - failed to configure"
+    fi
+    
+    make install 1> /dev/null
+    
+    ret=$?
+    
+    if [ $ret -ne 0 ]; then
+        bailout "$version - failed to build and install"
+    fi
+    
+    popd 1> /dev/null
+
 }
 
 function build_libgpg_error {
     # Only build if the binary doesn't exist already.
-    if [ ! -f "$PREFIX/bin/gpg-error-config" ]; then
-        version=$1-$2
-        fetch "ftp://ftp.gnupg.org/gcrypt/libgpg-error/$version.tar.bz2" $1
-    
-        pushd "$version" 1> /dev/null
-    
-        CFLAGS="-isysroot /Developer/SDKs/MacOSX10.6.sdk -arch x86_64 -arch i386" \
-        LDFLAGS="-framework CoreFoundation" \
-        ./configure --prefix="$PREFIX" --disable-shared --disable-dependency-tracking \
-        --with-libintl-prefix="$PREFIX" 1> /dev/null
-    
-        make install 1> /dev/null
-    
-        popd 1> /dev/null
+    if [ -f "$PREFIX/bin/gpg-error-config" ]; then
+        return;
     fi
+    
+    version=$1-$2
+    fetch "ftp://ftp.gnupg.org/gcrypt/libgpg-error/$version.tar.bz2" $1
+
+    # Check if the package was successfully extracted
+    if [ ! -d "$version" ]; then
+        bailout "$version directory doesn't exist."
+    fi
+    
+    pushd "$version" 1> /dev/null
+
+    CFLAGS="-isysroot /Developer/SDKs/MacOSX10.6.sdk -arch x86_64 -arch i386" \
+    LDFLAGS="-framework CoreFoundation" \
+    ./configure --prefix="$PREFIX" --disable-shared --disable-dependency-tracking \
+    --with-libintl-prefix="$PREFIX" 1> /dev/null
+    
+    ret=$?
+    
+    if [ $ret -ne 0 ]; then
+        bailout "$version - failed to configure"
+    fi
+    
+    make install 1> /dev/null
+    
+    ret=$?
+    
+    if [ $ret -ne 0 ]; then
+        bailout "$version - failed to build and install"
+    fi
+
+    popd 1> /dev/null
+
 }
 
 function build_libassuan {
     # Only build if the binary doesn't exist already.
-    if [ ! -f "$PREFIX/bin/libassuan-config" ]; then
-        version=$1-$2
-        fetch "ftp://ftp.gnupg.org/gcrypt/libassuan/$version.tar.bz2" $1
     
-        pushd "$version" 1> /dev/null
-    
-        CFLAGS="-isysroot /Developer/SDKs/MacOSX10.6.sdk -arch x86_64 -arch i386" \
-        ./configure --prefix="$PREFIX" --disable-shared --disable-dependency-tracking \
-        --with-gpg-error-prefix="$PREFIX" 1> /dev/null
-    
-        make install 1> /dev/null
-    
-        popd 1> /dev/null
+    if [ -f "$PREFIX/bin/libassuan-config" ]; then
+        return;
     fi
+    
+    version=$1-$2
+    fetch "ftp://ftp.gnupg.org/gcrypt/libassuan/$version.tar.bz2" $1
+
+    # Check if the package was successfully extracted
+	if [ ! -d "$version" ]; then
+	    bailout "$version directory doesn't exist."
+	fi
+
+    pushd "$version" 1> /dev/null
+
+    CFLAGS="-isysroot /Developer/SDKs/MacOSX10.6.sdk -arch x86_64 -arch i386" \
+    ./configure --prefix="$PREFIX" --disable-shared --disable-dependency-tracking \
+    --with-gpg-error-prefix="$PREFIX" 1> /dev/null
+    
+    ret=$?
+
+    if [ $ret -ne 0 ]; then
+        bailout "$version - failed to configure"
+    fi
+    
+    make install 1> /dev/null
+    
+    ret=$?
+    
+    if [ $ret -ne 0 ]; then
+        bailout "$version - failed to build and install"
+    fi
+    
+    popd 1> /dev/null
+
 }
 
 function build_gpgme {
     # Only build if the binary doesn't exist already.
-    if [ ! -f "$PREFIX/bin/gpgme-config" ]; then
-        version=$1-$2
-        fetch "ftp://ftp.gnupg.org/gcrypt/gpgme/$version.tar.bz2" $1
-    
-        pushd "$version" 1> /dev/null
-    
-        CFLAGS="-isysroot /Developer/SDKs/MacOSX10.6.sdk -arch x86_64 -arch i386" \
-        ./configure --prefix="$PREFIX" --enable-static --disable-shared \
-        --disable-dependency-tracking --with-gpg-error-prefix="$PREFIX" \
-        --with-gpg="$PREFIX/bin/gpg" --with-libassuan-prefix="$PREFIX" \
-        --without-pth --disable-glibtest 1> /dev/null
-    
-        make install 1> /dev/null
-    
-        popd 1> /dev/null
+    if [ -f "$PREFIX/bin/gpgme-config" ]; then
+        return;
     fi
+    
+    version=$1-$2
+    fetch "ftp://ftp.gnupg.org/gcrypt/gpgme/$version.tar.bz2" $1
+
+    # Check if the package was successfully extracted
+	if [ ! -d "$version" ]; then
+	    bailout "$version directory doesn't exist."
+	fi
+
+    pushd "$version" 1> /dev/null
+
+    CFLAGS="-isysroot /Developer/SDKs/MacOSX10.6.sdk -arch x86_64 -arch i386" \
+    ./configure --prefix="$PREFIX" --enable-static --disable-shared \
+    --disable-dependency-tracking --with-gpg-error-prefix="$PREFIX" \
+    --with-gpg="$PREFIX/bin/gpg" --with-libassuan-prefix="$PREFIX" \
+    --without-pth --disable-glibtest 1> /dev/null
+    
+    ret=$?
+    
+    if [ $ret -ne 0 ]; then
+        bailout "$version - failed to configure"
+    fi
+    
+    make install 1> /dev/null
+    
+    ret=$?
+    
+    if [ $ret -ne 0 ]; then
+        bailout "$version - failed to build and install"
+    fi
+    
+    popd 1> /dev/null
 }
 
 function build {
-    build_gettext ${GETTEXT_VERSION}
-    build_libgpg_error ${LIBGPG_ERROR_VERSION}
-    build_libassuan ${LIBASSUAN_VERSION}
-    build_gpgme ${GPGME_VERSION}
+    build_gettext "gettext" "${GETTEXT_VERSION}"
+    build_libgpg_error "libgpg-error" "${LIBGPG_ERROR_VERSION}"
+    build_libassuan "libassuan" "${LIBASSUAN_VERSION}"
+    build_gpgme "gpgme" "${GPGME_VERSION}"
 }
 
 function clean {
@@ -159,3 +271,6 @@ else
 fi
 
 popd 1> /dev/null
+
+echo "gpgme was built successfully."
+exit 0
